### ISSUE TITLE
Cannot create and/or save figures for column "manufacturer"

### ISSUE THREAD

**Issue by PaulWolfram** [fjodor/functional-programming#1]
Thanks for the video and for providing your code. I tried running your code and I am running into an issue if I want to save the figures from the for loop over all manufacturers (column `manufacturer`). For some reason no figures are being saved. The code is identical, I am just replacing column `manuf_c` with `manufacturer`. Thanks in advance for any tips!

``for(i in levels(mpg$manufacturer)) { 
  p <- mpg %>%  
    filter(manufacturer == i) %>% 
    ggplot(aes(x = displ, y = cty)) +
    geom_point(size = 3) +
    geom_smooth(method = "lm", color = "blue") +
    labs(title = "Fuel Eff vs. Displmt",
         subtitle = paste("Manufacturer:", i),
         x = "Displacement", y = "City Miles per Gallon")
  print(p)
  ggsave(p, filename = paste0("mpg_", i, ".png"))
}``

**Comment by fjodor** [comment]
Convert manufacturer to a factor first, like I did with manuf_c.

mpg <- mpg %>% 
  mutate(manufacturer = factor(manufacturer))
  
 Then run your code.
